### PR TITLE
[WIP] Support x and y direction at same time (aka grid)

### PR DESCRIPTION
**Pull request by koemeet**
I've found some time to hack around in this addon and try to implement grid support. It's harder than I thought.. Don't review it, I leave this here so maybe someone else can maybe make it work. I don't have the time right now to dig into it more (deadlines..), maybe someone else will :+1: 

This is related to #75

### CODE REVIEW

**Comment by jgwhite** [comment]
Thanks for taking a crack at it :) This is something I haven’t had the confidence or clarity to tackle.

**Comment by jgwhite** [comment]
@koemeet is this something you’re still interested in pursuing? If not, do you mind if I close this PR?

**Comment by saygun** [comment]
Is there any update about this one?

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we’re doing a bit of spring cleaning of older issues and pull requests. This pull request hasn’t been touched in a while so we’re closing it.

Please feel free to re-open if you’d like to resume work on it.

**Pull request closed without merging**
