### PR TITLE
Remove jQuery

### PR DESCRIPTION
**Pull request by omairvaiyani**
WIP: some tests are broken but appears to be functional

### CODE REVIEW

**Comment by jgwhite** [comment]
Many thanks for the PR! Apologies that `reorder` has become a blocker. Would you like to try cherry-picking the changes in #160 into this PR to test your hypothesis?

**Comment by omairvaiyani** [comment]
@jgwhite I'll take a look as soon as possible!

**Comment by omairvaiyani** [comment]
I'm unable to work on this for the foreseeable future! If anyone wants to pick up the remaining crumbs and get the build passing, feel free to fork the branch !

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we’re doing a bit of spring cleaning of older issues and pull requests. This pull request hasn’t been touched in a while so we’re closing it. Thank you so much for all your hard work.

Please feel free to re-open if you’d like to resume work on it.

**Comment by omairvaiyani** [comment]
Hi - we're still very reliant on this addon and are currently using my forked version on our production app. I will wait until Heroku's team have done some work on the project before re-issuing a PR; just incase significant refactoring is done.

**Comment by jgwhite** [comment]
@omairvaiyani thanks for your patience. We’re going to focus on updating dependencies and project health, which should clear the way for your work 👍

**Pull request closed without merging**
