### PR TITLE
Add warning to polyfill `Element.closest()`

### LINKED ISSUE #241: Element.closest() is unsupported in IE
**Describe the bug**
The use of `Element.closest()` was introduced in #212, causing the `_primeDrag` event to fail on IE 10/11 as the method is unsupported.

**To Reproduce**
1. Open the demo pages in IE10
2. Observe JS errors

**Additional context**
I think this just needs a doc change to call out browser support explicitly, and warning that consumers will need to polyfill in app code.

Happy to raise a PR for this!

### PR DESCRIPTION
**Pull request by samhogg**
Fixes #241

### CODE REVIEW

**Comment by btecu** [comment]
Adding a warning doesn't really fix the issue. The addon should avoid using `Element.closest`.

**Comment by samhogg** [comment]
@btecu open to that, too - although this was what I proposed in #241.

I don't think it's unreasonable to ask consumers of the library to polyfill, but can see the benefits of avoiding `Element.closest()` altogether.

**Comment by jgwhite** [comment]
While it’s true that this isn’t a solution, it’s definitely an improvement. I’ll reopen the issue once this is merged.

**Comment by jgwhite** [comment]
Thanks @samhogg!

**Pull request merged**
